---
- id: check-rebase-required
  name: Check if rebase is required
  description: This hook checks to see if the current repo requires a rebase.
  entry: check-rebase-required
  language: python
  always_run: true
  pass_filenames: false
